# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include: ["*"]

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactSourcesDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'f635c088-1047-40e8-8c29-2e3b05a38010/f955fae1-be95-4094-bf98-2e55fc5e5985'
    vstsFeedPackagePublish: 'frontend'
    versionOption: 'patch'
